Updates for 3.21.0
* +3.21 / -3.17
* remove unimplemented image_compress
* update TODO.md
* add IMPORTING.md
* remove deprecated get_latest_imported_tags
* set up gpio_pl06 for all aarch64
* recent cloud-init can use dhcpcd just fine
* always install non-busybox mount for 3.18+ (base/5.conf)
* tiny-cloud >= 3.1.0 does autodetection
* AWS & Azure images can use the same VHD format options
* nvme module is already enabled in cmdline/initramfs
* drop AWS NVMe core timeout setting for 3.21+
* switch GCP image format to "raw.tar.gz"
* enable GCP "gve" module on cmdline/initramfs
* drop setting "ntp_server", chrony will use default
* "generic" cloud should include all options for other clouds
* "generic" tiny-cloud starts with 3.21 (because of autodetection)
* move "sudo deprecated/removed" motd's out of version and into base configs
* cmdline console= for both x86_64 and aarch64 moved to base/1.conf
* ImageConfig.CONVERT_CMD resize raw image to 1 GiB before tar.gz
* ImageStorage.run() optionally supports shell string instead of individual args (for multi-step image conversions)
* don't disable getty on tty1 for those who need to login via VGA terminal (nocloud, etc?)

diff --git a/scripts/setup-tiny b/scripts/setup-tiny
--- a/scripts/setup-tiny
+++ b/scripts/setup-tiny
@@ -27,8 +27,15 @@ else
     sed -i.bak -Ee "s/^#?CLOUD_USER=.*/CLOUD_USER=$IMAGE_LOGIN/" "$TC_CONF"
     rm "$TC_CONF.bak"
 
-    # tiny-cloud >= 3.0.0 sets up init scripts with /sbin/tiny-cloud --setup
-    if [ -f "$TARGET/sbin/tiny-cloud" ]; then
+    if [ -f "$TARGET/usr/sbin/tiny-cloud" ]; then
+        # tiny-cloud >= 3.1.0 is in /usr/sbin
+        chroot "$TARGET" /usr/sbin/tiny-cloud --enable
+    elif greater_or_equal "$VERSION" 3.21; then
+        # 3.18 has tiny-cloud 3.1.0, and we didn't find what we expected
+        echo "Error: /usr/sbin/tiny-cloud not found" >&2
+        exit 1
+    elif [ -f "$TARGET/sbin/tiny-cloud" ]; then
+        # tiny-cloud >= 3.0.0 sets up init scripts with /sbin/tiny-cloud --setup
         chroot "$TARGET" /sbin/tiny-cloud --enable
     elif greater_or_equal "$VERSION" 3.18; then
         # 3.18 has tiny-cloud 3.0.0, and we didn't find what we expected
